/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'episodes' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'coverImage' : IDL.Text,
  'genre' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllComics' : IDL.Func([], [IDL.Vec(Comic)], ['query']),
  'getAllGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getComicById' : IDL.Func([IDL.Nat], [IDL.Opt(Comic)], ['query']),
  'getComicsByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Comic)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'episodes' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'coverImage' : IDL.Text,
    'genre' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllComics' : IDL.Func([], [IDL.Vec(Comic)], ['query']),
    'getAllGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getComicById' : IDL.Func([IDL.Nat], [IDL.Opt(Comic)], ['query']),
    'getComicsByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Comic)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };