/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comic {
  'id' : bigint,
  'title' : string,
  'episodes' : bigint,
  'description' : string,
  'author' : string,
  'likes' : bigint,
  'coverImage' : string,
  'genre' : string,
}
export interface FaqItem {
  'id' : bigint,
  'question' : string,
  'createdAt' : bigint,
  'answer' : string,
  'viewCount' : bigint,
  'approved' : boolean,
  'notHelpfulCount' : bigint,
  'category' : string,
  'helpfulCount' : bigint,
}
export interface SubmittedQuestion {
  'id' : bigint,
  'status' : string,
  'question' : string,
  'name' : [] | [string],
  'submittedAt' : bigint,
  'answer' : string,
  'email' : [] | [string],
}
export interface _SERVICE {
  'answerQuestion' : ActorMethod<[string, bigint, string], boolean>,
  'approveQuestion' : ActorMethod<[string, bigint, string], boolean>,
  'getAllApprovedFaqs' : ActorMethod<[], Array<FaqItem>>,
  'getAllComics' : ActorMethod<[], Array<Comic>>,
  'getAllGenres' : ActorMethod<[], Array<string>>,
  'getAllSubmittedQuestions' : ActorMethod<[], Array<SubmittedQuestion>>,
  'getComicById' : ActorMethod<[bigint], [] | [Comic]>,
  'getComicsByGenre' : ActorMethod<[string], Array<Comic>>,
  'getFaqsByCategory' : ActorMethod<[string], Array<FaqItem>>,
  'getPopularFaqs' : ActorMethod<[], Array<FaqItem>>,
  'recordFaqView' : ActorMethod<[bigint], boolean>,
  'rejectQuestion' : ActorMethod<[string, bigint], boolean>,
  'submitQuestion' : ActorMethod<
    [[] | [string], [] | [string], string],
    bigint
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
  'voteHelpful' : ActorMethod<[bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];